#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"
# exec echo ' ' | sudo -S /etc/NX/nxserver --startup

# feh --bg-scale "$SCRIPTPATH"/background.png 2>&1 &
# feh --bg-scale "/usr/share/blackarch/artwork/wallpaper"/capturingivs-three.jpg 2>&1 &
feh --bg-scale ./background.png 2>&1 &

# xrandr change steamdeck rotate
# xrandr --output eDP-1 --rotate right
# xrandr --output eDP-1 --mode 800x1280 --pos 0x1440 --rotate right --output DP-1 --primary --mode 3440x1440 --pos 0x0 --rotate normal

####remote
# nxss &
# nomachine-bore &

leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"
