modkey = "Mod1"
mousekey = "Mod1"
# workspaces = [{x=0,y=0,width=3840,height=2160}]
# workspaces = [{x=0,y=0,width=,height=2160}]
workspaces = []
tags = ["Clutter", "Conscious", "Thinking", "CS", "Rust", "Enjoy", "Communicate", "Eight", "Company"]
layouts = ["MainAndVertStack", "MainAndHorizontalStack", "MainAndDeck", "GridHorizontal", "EvenHorizontal", "EvenVertical", "Fibonacci", "LeftMain", "CenterMain", "CenterMainBalanced", "CenterMainFluid", "Monocle", "RightWiderLeftStack", "LeftWiderRightStack"]
# Tag,Workspace
layout_mode = "Workspace"
insert_behavior = "Bottom"
scratchpad = [
    { name = "Htop", value = "htop", x = 860, y = 390, height = 300, width = 200 },
]
window_rules = []
disable_current_tag_swap = true
disable_tile_drag = false
# Sloppy,ClickTo,Driven
focus_behaviour = "Sloppy"
focus_new_windows = true
# max_window_width = 0.9

# [[workspaces]]
# x=0
# y=0
# height=600
# width=1000
# workspaces = [
    # { y = 0, x = 0, height = 1440, width = 1720 },
    # { y = 0, x = 1720, height = 1440, width = 1720 },
# ]

# [[scratchpad]]
# name = "htop" # This is the name which is referenced when calling (case-sensitive)
# value = "htop" # The command to load the application if it isn't started
# # value = "WINIT_X11_SCALE_FACTOR=1 htop" #with float values
# # x, y, width, height are in pixels when an integer is inputted or a percentage when a float is inputted.
# # These values are relative to the size of the workspace, and will be restricted depending on the workspace size.
# x = 860
# y = 390
# height = 300
# width = 200

#######Keybind########
###Execute

[[keybind]]
command = "Execute"
value = "brightnessctl set 5%-"
modifier = []
key = "XF86MonBrightnessDown"

[[keybind]]
command = "Execute"
value = "brightnessctl set +5%"
modifier = []
key = "XF86MonBrightnessUp"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume @DEFAULT_SINK@ +5%"
modifier = []
key = "XF86AudioRaiseVolume"

[[keybind]]
command = "Execute"
value = "pactl set-sink-volume @DEFAULT_SINK@ -5%"
modifier = []
key = "XF86AudioLowerVolume"

[[keybind]]
command = "Execute"
value = "pactl set-sink-mute @DEFAULT_SINK@ toggle"
modifier = []
key = "XF86AudioMute"

[[keybind]]
command = "Execute"
value = "pactl set-source-mute @DEFAULT_SOURCE@ toggle"
modifier = []
key = "XF86AudioMicMute"

[[keybind]]
command = "Execute"
value = "playerctl play-pause"
modifier = []
key = "XF86AudioPlay"

[[keybind]]
command = "Execute"
value = "playerctl next"
modifier = []
key = "XF86AudioNext"

[[keybind]]
command = "Execute"
value = "playerctl previous"
modifier = []
key = "XF86AudioPrev"

[[keybind]]
command = "Execute"
value = "dmenu_run"
modifier = []
key = "XF86Search"

[[keybind]]
command = "Execute"
value = "netease-cloud-music"
modifier = []
key = "XF86Search"

[[keybind]]
command = "Execute"
value = "grim $HOME/screenshots/$(date +'%s_grim.png')"
modifier = []
key = "Print"

# [[keybind]]
# command = "Execute"
# value = "brightnessctl -q sset 5%+"
# modifier = []
# key = "XF86XK_MonBrightnessUp"

# [[keybind]]
# command = "Execute"
# value = "brightnessctl -q sset 5%-"
# modifier = []
# key = "XF86XK_MonBrightnessDown"

[[keybind]]
command = "Execute"
value = "rofi -show power-menu -modi power-menu:$HOME/.config/leftwm/themes/current/rofi-power-menu.sh"
modifier = []
key = "XF86XK_PowerOff"

# [[keybind]]
# command = "Execute"
# value = "dmenu_run -i -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=14'"
# modifier = ["modkey"]
# key = "d"

[[keybind]]
command = "Execute"
value = "rofi -show combi -combi-modi window,run,ssh -modi combi -theme /usr/share/rofi/themes/gruvbox-dark-soft.rasi"
modifier = ["modkey"]
key = "d"

# [[keybind]]
# command = "Execute"
# value = "xfce4-terminal"
# modifier = ["modkey"]
# key = "Return"
[[keybind]]
command = "Execute"
value = "alacritty"
modifier = ["modkey"]
key = "Return"

[[keybind]]
command = "Execute"
value = "goldendict"
modifier = ["Control"]
key = "g"

[[keybind]]
command = "Execute"
value = "flameshot gui"
modifier = ["Mod4"]
key = "x"

[[keybind]]
command = "Execute"
value = "Thunar"
modifier = ["Mod4"]
key = "e"

[[keybind]]
command = "Execute"
value = "loginctl kill-session $XDG_SESSION_ID"
modifier = ["modkey", "Shift"]
key = "x"

[[keybind]]
command = "Execute"
value = "slock"
modifier = ["modkey", "Control"]
key = "l"

###leftwm shortkey
[[keybind]]
command = "CloseWindow"
value = ""
modifier = ["modkey"]
key = "q"

[[keybind]]
command = "SoftReload"
value = ""
modifier = ["modkey", "Shift"]
key = "r"
# [[keybind]]
# command = "HardReload"
# value = ""
# modifier = ["modkey", "Shift"]
# key = "r"


[[keybind]]
command = "MoveToLastWorkspace"
value = ""
modifier = ["modkey", "Shift"]
key = "w"

[[keybind]]
command = "SwapTags"
value = ""
modifier = ["modkey"]
key = "w"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "k"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "j"

[[keybind]]
command = "MoveWindowTop"
value = ""
modifier = ["modkey","Shift"]
key = "Return"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "k"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "j"

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Control"]
key = "k"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "j"

[[keybind]]
command = "SetLayout"
value = "Monocle"
modifier = ["modkey","Control"]
key = "m"

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "l"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "h"

[[keybind]]
command = "MoveWindowUp"
value = ""
modifier = ["modkey", "Shift"]
key = "Up"

[[keybind]]
command = "MoveWindowDown"
value = ""
modifier = ["modkey", "Shift"]
key = "Down"

[[keybind]]
command = "FocusWindowUp"
value = ""
modifier = ["modkey"]
key = "Up"

[[keybind]]
command = "FocusWindowDown"
value = ""
modifier = ["modkey"]
key = "Down"

[[keybind]]
command = "NextLayout"
value = ""
modifier = ["modkey", "Control"]
key = "Up"

[[keybind]]
command = "PreviousLayout"
value = ""
modifier = ["modkey", "Control"]
key = "Down"

[[keybind]]
command = "FocusWorkspaceNext"
value = ""
modifier = ["modkey"]
key = "Right"

[[keybind]]
command = "FocusWorkspacePrevious"
value = ""
modifier = ["modkey"]
key = "Left"

[[keybind]]
command = "GotoTag"
value = "1"
modifier = ["modkey"]
key = "1"

[[keybind]]
command = "GotoTag"
value = "2"
modifier = ["modkey"]
key = "2"

[[keybind]]
command = "GotoTag"
value = "3"
modifier = ["modkey"]
key = "3"

[[keybind]]
command = "GotoTag"
value = "4"
modifier = ["modkey"]
key = "4"

[[keybind]]
command = "GotoTag"
value = "5"
modifier = ["modkey"]
key = "5"

[[keybind]]
command = "GotoTag"
value = "6"
modifier = ["modkey"]
key = "6"

[[keybind]]
command = "GotoTag"
value = "7"
modifier = ["modkey"]
key = "7"

[[keybind]]
command = "GotoTag"
value = "8"
modifier = ["modkey"]
key = "8"

[[keybind]]
command = "GotoTag"
value = "9"
modifier = ["modkey"]
key = "9"

[[keybind]]
command = "MoveToTag"
value = "1"
modifier = ["modkey", "Shift"]
key = "1"

[[keybind]]
command = "MoveToTag"
value = "2"
modifier = ["modkey", "Shift"]
key = "2"

[[keybind]]
command = "MoveToTag"
value = "3"
modifier = ["modkey", "Shift"]
key = "3"

[[keybind]]
command = "MoveToTag"
value = "4"
modifier = ["modkey", "Shift"]
key = "4"

[[keybind]]
command = "MoveToTag"
value = "5"
modifier = ["modkey", "Shift"]
key = "5"

[[keybind]]
command = "MoveToTag"
value = "6"
modifier = ["modkey", "Shift"]
key = "6"

[[keybind]]
command = "MoveToTag"
value = "7"
modifier = ["modkey", "Shift"]
key = "7"

[[keybind]]
command = "MoveToTag"
value = "8"
modifier = ["modkey", "Shift"]
key = "8"

[[keybind]]
command = "MoveToTag"
value = "9"
modifier = ["modkey", "Shift"]
key = "9"

# [[keybind]]
# command = "ToggleScratchPad"
# value = ""
# modifier = ["modkey"]
# key = "-"

[[keybind]]
command = "MoveWindowToPreviousWorkspace"
modifier = ["modkey", "Shift"]
key = "Left"

# [[keybind]]
# command = "FloatingToTile"
# modifier = ["modkey","Shift"]
# key = "t"

# [[keybind]]
# command = "TileToFloating"
# modifier = ["modkey", "Shift"]
# key = "f"

[[keybind]]
command = "ToggleFloating"
modifier = ["modkey", "Control"]
key = "f"

[[keybind]]
command = "ToggleFullScreen"
modifier = ["modkey"]
key = "f"
