[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 1
[[repos.themes]]
name = "eden"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-eden/"
commit = "*"
version = "2.4.1"
leftwm_versions = "*"
current = false
[[repos.themes]]
name = "Orange Forest"
repository = "https://github.com/PVautour/leftwm-theme-orange-forest/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false
