# To add additional repos, you MUST specify a url, a UNIQUE ALPHANUMERIC name, and an empty array of themes
# e.g.:
border_width = 3
margin = 0
default_border_color = "#32302f"
floating_border_color = "#32302f"
focused_border_color = "#698B22"

[[gutter]]
side = "Top"
value = 0

