#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"
# exec echo ' ' | sudo -S /etc/NX/nxserver --startup

# feh --bg-scale "$SCRIPTPATH"/background.png 2>&1 &
feh --bg-scale "/usr/share/blackarch/artwork/wallpaper"/capturingivs-three.jpg 2>&1 &

####remote
# nxss &
# nomachine-bore &

leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"
